backend:
  name: git-gateway
  branch: master
  squash_merges: true

locale: "es"

publish_mode: editorial_workflow
show_preview_links: false

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: https://biodiversidad-provita.netlify.app/

editor:
   preview: false

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: content/home/content.json
        label: "Página principal"
        name: "home"
        media_folder: "./images"
        fields:
          - {label: "Id", name: "id", widget: "hidden", required: true}
          - {label: "Introducción", name: "intro", widget: "object", fields: [
              {label: "En español", name: "es", widget: "markdown", buttons: ["bold", "italic", "link"], editor_components: []},
              {label: "En inglés", name: "en", widget: "markdown", buttons: ["bold", "italic", "link"], editor_components: []}]}
          - {label: "Fichas de página", summary: "{{fields.title.es}} ({{fields.title.en}})", name: "cards", widget: "list", fields: [
              {label: "Título", name: "title", widget: "object", fields: [
                {label: "En español", name: "es", widget: "string"},
                {label: "En inglés", name: "en", widget: "string"}]},
              {label: "Descripción", name: "summary", widget: "object", fields: [
                {label: "En español", name: "es", widget: "markdown", modes: ["raw"]},
                {label: "En inglés", name: "en", widget: "markdown", modes: ["raw"]}]},
              {label: "Enlace", name: "link", widget: "string"},
              {label: "Imagen", name: "image", widget: "image", allow_multiple: false}]}
      - file: content/about/content.json
        label: "Acerca de"
        name: "about"
        media_folder: "./images"
        fields:
          - {label: "Id", name: "id", widget: "hidden", required: true}
          - {label: "Título", name: "bannerText", widget: "object", fields: [
              {label: "En español", name: "es", widget: "string"},
              {label: "En inglés", name: "en", widget: "string"}]}
          - {label: "Descripción", name: "summaryText", widget: "object", fields: [
              {label: "En español", name: "es", widget: "markdown", modes: ["raw"]},
              {label: "En inglés", name: "en", widget: "markdown", modes: ["raw"]}]}
      - file: content/occurrences/content.json
        label: "Registros de presencia"
        name: "occurrences"
        media_folder: "./images"
        fields:
          - {label: "Id", name: "id", widget: "hidden", required: true}
          - {label: "Título", name: "bannerText", widget: "object", fields: [
              {label: "En español", name: "es", widget: "string"},
              {label: "En inglés", name: "en", widget: "string"}]}
      - file: content/datasets/content.json
        label: "Juegos de datos"
        name: "datasets"
        media_folder: "./images"
        fields:
          - {label: "Id", name: "id", widget: "hidden", required: true}
          - {label: "Título", name: "bannerText", widget: "object", fields: [
              {label: "En español", name: "es", widget: "string"},
              {label: "En inglés", name: "en", widget: "string"}]}
      - file: content/ecosystems/content.json
        label: "Ecosistemas"
        name: "ecosystems"
        media_folder: "./images"
        fields:
          - {label: "Id", name: "id", widget: "hidden", required: true}
          - {label: "Título", name: "bannerText", widget: "object", fields: [
              {label: "En español", name: "es", widget: "string"},
              {label: "En inglés", name: "en", widget: "string"}]}
          - {label: "Descripción", name: "summaryText", widget: "object", fields: [
              {label: "En español", name: "es", widget: "markdown", modes: ["raw"]},
              {label: "En inglés", name: "en", widget: "markdown", modes: ["raw"]}]}
      - file: content/faunarb/content.json
        label: "Fauna amenazada"
        name: "faunarb"
        media_folder: "./images"
        fields:
          - {label: "Id", name: "id", widget: "hidden", required: true}
          - {label: "Título", name: "bannerText", widget: "object", fields: [
              {label: "En español", name: "es", widget: "string"},
              {label: "En inglés", name: "en", widget: "string"}]}
          - {label: "Descripción", name: "summaryText", widget: "object", fields: [
              {label: "En español", name: "es", widget: "markdown", modes: ["raw"]},
              {label: "En inglés", name: "en", widget: "markdown", modes: ["raw"]}]}
          - {label: "Texto de ayuda del gráfico", name: "chartHelpText", widget: "object", fields: [
              {label: "En español", name: "es", widget: "markdown", modes: ["raw"]},
              {label: "En inglés", name: "en", widget: "markdown", modes: ["raw"]}]}
